project:
  type: website
  preview:
    host: "127.0.0.1"
    port: 4200
    browser: true
    watch-inputs: true

metadata-files:
  - posts/_metadata.yml

website:
  title: "hyper-shotgun"
  description: none
  site-url: https://jope35.github.io/hypershotgun-blog/
  favicon: favicons/hyper_favi.png
  image: favicons/HS_logo.png
  navbar:
    logo: apple-touch-icon.png
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/joostdetheije/
      - icon: github
        text: Github
        href: https://github.com/jope35
  # page-footer:
  #   center:
  #     - text: "About"
  #       href: about.qmd
  search:
    location: navbar
    type: overlay

format:
  html:
    # highlight-style: ayu #ayu, atom-one, arrow
    theme:
      dark: darkly
      light: flatly
    css: styles.css

execute:
  freeze: auto
