project:
  type: website
  preview:
    host: "127.0.0.1"
    port: 4200
    browser: true
    watch-inputs: true

metadata-files:
  - posts/_metadata.yml

website:
  title: "hyper-shotgun"
  description: none
  site-url: https://jope35.github.io/hypershotgun-blog/
  favicon: favicons/hyper_favi.png
  image: favicons/HS_logo.png
  navbar:
    logo: apple-touch-icon.png
    right:
      - whois.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/joostdetheije/
      - icon: github
        text: Github
        href: https://github.com/jope35
  search:
    location: navbar
    type: overlay

format:
  html:
    highlight-style: nord #ayu, atom-one, arrow, github, breeze, a11y, gruvbox
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto
